language: cpp
sudo: required
compiler:
- gcc
install:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/update_gcc_version.sh
  && chmod +x update_gcc_version.sh
  && ./update_gcc_version.sh 4.9
  && rm update_gcc_version.sh
- sudo apt-get install libfuse-dev
before_script:
- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/setup_biicode_project.sh
  && chmod +x setup_biicode_project.sh
  && ./setup_biicode_project.sh
  && rm setup_biicode_project.sh
script:
- bii cpp:build -- -j2
#- wget https://raw.githubusercontent.com/smessmer/travis-utils/master/run_with_fuse.sh
#  && chmod +x run_with_fuse.sh
#  && ./run_with_fuse.sh "./bin/messmer_copyfs_test_main"
#  && rm run_with_fuse.sh
after_success:
- bii user ${BII_USERNAME} -p ${BII_PASSWORD}
- bii publish
#deploy:
#  provider: biicode
#  user: ${BII_USERNAME}
#  password:
#    secure: ${BII_PASSWORD}
#  on:
#    branch: develop

